name: PHP

on: workflow_call

jobs:
  php:
    name: PHP
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ '8.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Paths filters
        uses: dorny/paths-filter@v2
        id: paths
        with:
          filters: |
            composer: &composer
              - 'composer.json'
              - 'composer.lock'
            php: &php
              - '**/*.php'
            phpcs:
              - *php
              - *composer
              - 'phpcs.xml'
          list-files: shell

      - name: Setup
        if: ${{ toJSON( steps.paths.outputs.changes ) != '"[]"' }}
        uses: ./.github/actions/setup-php
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        if: ${{ toJSON( steps.paths.outputs.changes ) != '"[]"' && steps.cache-php-dependencies.outputs.cache-hit != 'true' }}
        run: composer install --no-progress --no-interaction --no-ansi

      - name: List changed files
        if: ${{ steps.paths.outputs.phpcs == 'true' }}
        run: |
          echo ${{ steps.paths.outputs.php_files }}

      - name: Lint changed files
        id: phpcs
        if: ${{ steps.paths.outputs.phpcs == 'true' }}
        run: |
          vendor/bin/phpcs --report-full --report-checkstyle=./phpcs-report.xml ${{ steps.paths.outputs.php_files }}

      - name: Report PHPCS results
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: |
          vendor/bin/cs2pr ./phpcs-report.xml
